export default {
  questionType: {
    FORM_TYPE_SKU_COUNT: 'sku_count',
  },
  actionType: {
    ACTION_INFO: 'ACTION_INFO',
    ACTION_NEXT: 'ACTION_NEXT',
    ACTION_COUNT: 'ACTION_COUNT',
    ACTION_FORM_SUBMIT: 'ACTION_FORM_SUBMIT',
    ACTION_FORM_CLEAR: 'ACTION_FORM_CLEAR',
  },
  debugMode: {
    NO_DEBUG: 0,
    DEBUG_UI_SCREEN: 1,
  },
  questionButtonType: {
    QUESTION_BUTTON_DONE: 'QUESTION_BUTTON_DONE',
    QUESTION_BUTTON_NEXT: 'QUESTION_BUTTON_NEXT',
  },
  tabType: {
    TAB_TYPE_BOTTOM_BAR: 'TAB_TYPE_BOTTOM_BAR',
  },
  modalType: {
    MODAL_TYPE_CENTER: 'MODAL_TYPE_CENTER',
    MODAL_TYPE_BOTTOM: 'MODAL_TYPE_BOTTOM',
  },
};
