export default {
  questionType: {
    FORM_TYPE_SKU_COUNT: 'sku_count',
  },
  actionType: {
    ACTION_INFO: 'ACTION_INFO',
    ACTION_NEXT: 'ACTION_NEXT',
  },
  debugMode: {
    NO_DEBUG: 0,
    DEBUG_UI_SCREEN: 1,
  },
  questionButtonType: {
    QUESTION_BUTTON_DONE: 'QUESTION_BUTTON_DONE',
    QUESTION_BUTTON_NEXT: 'QUESTION_BUTTON_NEXT',
  },
  tabType: {
    TAB_TYPE_BOTTOM_BAR: 'TAB_TYPE_BOTTOM_BAR',
  },
  actionType: {
    ACTION_TYPE_COUNT_PLUS: 'ACTION_TYPE_COUNT_PLUS',
    ACTION_TYPE_COUNT_MINUS: 'ACTION_TYPE_COUNT_MINUS',
    ACTION_TYPE_FORM_SUBMIT: 'ACTION_TYPE_FORM_SUBMIT',
  },
  modalType: {
    MODAL_TYPE_CENTER: 'MODAL_TYPE_CENTER',
    MODAL_TYPE_BOTTOM: 'MODAL_TYPE_BOTTOM',
  },
};
