export default {
  dateFormat: {
    DATE_FORMAT_DATE_PICKER: 'YYYY/MM/DD',
    DATE_FORMAT_SHORT: 'MM/DD/YYYY',
    DATE_FORMAT_API: 'YYYY-MM-DD',
  },
  questionType: {
    FORM_TYPE_SKU_COUNT: 'sku_count',
    FORM_TYPE_SKU_SHELF_SHARE: 'sku_shelf_share',
    FORM_TYPE_SKU_SELECT: 'sku_select',
  },

  actionType: {
    ACTION_INFO: 'ACTION_INFO',
    ACTION_NEXT: 'ACTION_NEXT',
    ACTION_COUNT: 'ACTION_COUNT',
    ACTION_CHECK: 'ACTION_CHECK',
    ACTION_FORM_SUBMIT: 'ACTION_FORM_SUBMIT',
    ACTION_FORM_CLEAR: 'ACTION_FORM_CLEAR',
    ACTION_SELECT_ALL: 'ACTION_SELECT_ALL',
    ACTION_DONE: 'ACTION_DONE',
    ACTION_CAPTURE: 'ACTION_CAPTURE',
    ACTION_ADD: 'ACTION_ADD',
  },
  debugMode: {
    NO_DEBUG: 0,
    DEBUG_UI_SCREEN: 1,
  },
  questionButtonType: {
    QUESTION_BUTTON_DONE: 'QUESTION_BUTTON_DONE',
    QUESTION_BUTTON_NEXT: 'QUESTION_BUTTON_NEXT',
  },
  tabType: {
    TAB_TYPE_BOTTOM_BAR: 'TAB_TYPE_BOTTOM_BAR',
  },
  modalType: {
    MODAL_TYPE_CENTER: 'MODAL_TYPE_CENTER',
    MODAL_TYPE_BOTTOM: 'MODAL_TYPE_BOTTOM',
    MODAL_TYPE_FULL: 'MODAL_TYPE_FULL',
  },
  userType: {
    USER_TYPE_SUPER_ADMIN: 'Super Admin',
    USER_TYPE_ADMIN: 'Admin',
  },
  buttonType: {
    BUTTON_TYPE_SUMBIT: 'submit',
    BUTTON_TYPE_FORM_LINK: 'form_link',
    BUTTON_TYPE_CHECKIN_LINK: 'checkin_link',
  },
  actionItemType: {
    ACTION_ITEM_TYPE_ACTION: 'Action',
    ACTION_ITEM_TYPE_TASK: 'Task',
    ACTION_ITEM_TYPE_RED_FLAG_CHURN: 'Red Flag: Churn',
    ACTION_ITEM_TYPE_RED_FLAG_DECLINE: 'Red Flag: Decline',
  },
};
