export const CHANGE_LOGIN_STATUS = "CHANGE_LOGIN_STATUS";
export const SLIDE_STATUS = "SLIDE STATUS";
export const CHANGE_PROFILE_STATUS = "CHANGE_PROFILE_STATUS";
export const CHANGE_MORE_STATUS = "CHANGE_MORE_STATUS";
export const CHANGE_BOTTOM_TAB_LIST = "CHANGE_BOTTOM_TAB_LIST";
export const SHOW_MORE_COMPONENT = "SHOW_MORE_COMPONENT";