export const CHANGE_LOGIN_STATUS = "CHANGE_LOGIN_STATUS";
export const CHANGE_USER_INFO = "CHANGE_USER_INFO";

export const CHANGE_SELECT_PROJECT = "CHANGE_SELECT_PROJECT";
export const CHANGE_PROJECT_PAYLOAD = "CHANGE_PROJECT_PAYLOAD";
export const CHANGE_ACCESS_TOKEN = "CHANGE_ACCESS_TOKEN";

export const SLIDE_STATUS = "SLIDE STATUS";
export const BACK_ICON_STATUS = "BACK_ICON_STATUS";
export const CHANGE_PROFILE_STATUS = "CHANGE_PROFILE_STATUS";
export const CHANGE_MORE_STATUS = "CHANGE_MORE_STATUS";
export const SHOW_MORE_COMPONENT = "SHOW_MORE_COMPONENT";
export const CHANGE_LIBRARY_CHILD_STATUS = "CHANGE_LIBRARY_CHILD_STATUS";
export const CHANGE_CURRENT_LOCATION = "CHANGE_CURRENT_LOCATION";

// location action types
export const STATUS_PIN_KEY = "STATUS_PIN_KEY";
export const CHANGE_PIN_KEY = "CHANGE_PIN_KEY";
export const STATUS_LOCATION_MAP = "STATUS_LOCATION_MAP";
export const CHANGE_LOCATION_MAP = "CHANGE_LOCATION_MAP";
export const STATUS_LOCATION_FILTERS = "STATUS_LOCATION_FILTERS";
export const CHANGE_LOCATION_FILTERS = "CHANGE_LOCATION_FILTERS";
export const STATUS_LOCATION_SEARCH_LISTS = "STATUS_LOCATION_SEARCH_LISTS";
export const CHANGE_LOCATION_SEARCH_LISTS = "CHANGE_LOCATION_SEARCH_LISTS";
export const STATUS_LOCATION_INFO = "STATUS_LOCATION_INFO";
export const CHANGE_LOCATION_INFO = "CHANGE_LOCATION_INFO";
export const STATUS_STAGE_OUTCOME_UPDATE = "STATUS_STAGE_OUTCOME_UPDATE";